version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: stockcontrol
      POSTGRES_USER: stock
      POSTGRES_PASSWORD: stock
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: