spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stockcontrol?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: stock
    password: stock

  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:db/migration
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
